apiVersion: v1
kind: Service
metadata:
  name: ignite-discovery-service
  namespace: ignite
  labels:
    app: ignite
spec:
  type: None
  ports:
    - name: discovery
      port: 47500
  selector:
    labels:
      app: ignite
